# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.BigIntegerField()),
                ('year', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=16)),
                ('nr_of_episodes', models.IntegerField()),
                ('highest_episode_number', models.IntegerField()),
                ('special_ep_count', models.IntegerField()),
                ('air_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('url', models.CharField(max_length=512, null=True)),
                ('picname', models.CharField(max_length=128, null=True)),
                ('rating', models.FloatField(null=True)),
                ('vote_count', models.IntegerField()),
                ('temp_rating', models.FloatField(null=True)),
                ('temp_vote_count', models.IntegerField()),
                ('average_review_rating', models.FloatField(null=True)),
                ('review_count', models.IntegerField()),
                ('is_18_restricted', models.IntegerField()),
                ('description', models.CharField(max_length=8192, null=True)),
                ('ann_id', models.BigIntegerField(null=True)),
                ('allcinema_id', models.BigIntegerField(null=True)),
                ('animenfo_id', models.CharField(max_length=64, null=True)),
                ('anidb_updated', models.DateTimeField()),
                ('special_count', models.IntegerField()),
                ('credit_count', models.IntegerField()),
                ('other_count', models.IntegerField()),
                ('trailer_count', models.IntegerField()),
                ('parody_count', models.IntegerField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'anime',
            },
        ),
        migrations.CreateModel(
            name='AnimeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_pk', models.BigIntegerField()),
                ('related_aid', models.BigIntegerField()),
                ('relation_type', models.CharField(choices=[('sequel', 'sequel'), ('prequel', 'prequel'), ('same setting', 'same setting'), ('alternative setting', 'alternative setting'), ('alternative version', 'alternative version'), ('music video', 'music video'), ('character', 'character'), ('side story', 'side story'), ('parent story', 'parent story'), ('summary', 'summary'), ('full story', 'full story'), ('other', 'other')], max_length=20)),
            ],
            options={
                'db_table': 'anime_relation',
            },
        ),
        migrations.CreateModel(
            name='AnimeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.BigIntegerField()),
                ('titletype', models.CharField(max_length=512)),
                ('lang', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'anime_title',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.BigIntegerField()),
                ('eid', models.BigIntegerField()),
                ('length', models.IntegerField()),
                ('rating', models.FloatField(null=True)),
                ('votes', models.IntegerField()),
                ('epno', models.CharField(max_length=8)),
                ('title_eng', models.CharField(max_length=256, null=True)),
                ('title_romaji', models.CharField(max_length=256, null=True)),
                ('title_kanji', models.CharField(max_length=256, null=True)),
                ('aired', models.DateField(null=True)),
                ('type', models.CharField(choices=[('regular', 'regular'), ('special', 'special'), ('credit', 'credit'), ('trailer', 'trailer'), ('parody', 'parody'), ('other', 'other')], max_length=10)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'episode',
            },
        ),
    ]
